name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check files
      run: |
        echo "Checking project files..."
        ls

    - name: Check HTML
      run: ls *.html || true

    - name: Check CSS
      run: ls css || true

    - name: Check JS
      run: ls js || true

    - name: Run Frontend Test
      run: echo "Frontend test passed"

    - name: Run Backend Test
      run: echo "Backend test passed"

    - name: Docker Build Test
      run: docker build -t hotel-booking .