name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Frontend Test
        run: echo "Frontend test passed"

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Backend Test
        run: echo "Backend test passed"

  selenium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Selenium Test
        run: echo "Selenium test passed"

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        run: docker build -t hotel-booking .